src/Entity/Devis.php
<?php

namespace App\Entity;

use DateTime;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use App\Outil\Outil;
use Doctrine\Persistence\Event\LifecycleEventArgs;
use App\Repository\DevisRepository;
use Doctrine\ORM\Mapping\PrePersist;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo; 


/**
 * @ORM\Entity(repositoryClass=DevisRepository::class)
 */
class Devis
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\ManyToOne(targetEntity=Statue::class, inversedBy="devis")
     */
    private $statue;

    /**
     * @ORM\ManyToOne(targetEntity=Clients::class, inversedBy="devis")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\OneToMany(targetEntity=Lignedevis::class, mappedBy="devis", cascade={"persist", "remove"})
     */
    private $lignedevis;

    /**
     * @var DateTime $created
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=false)
     * @Gedmo\Timestampable(on="create")
     */
    protected $createdAt;

    /**
     * @var DateTime $updated
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=false)
     * @Gedmo\Timestampable(on="update")
     */
    protected $updatedAt;

    public function __construct()
    {
        $this->lignedevis = new ArrayCollection();
    }

    public function __toString(){
        return $this->nom;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getStatue(): ?Statue
    {
        return $this->statue;
    }

    public function setStatue(?Statue $statue): self
    {
        $this->statue = $statue;

        return $this;
    }

    public function getClient(): ?Clients
    {
        return $this->client;
    }

    public function setClient(?Clients $client): self
    {
        $this->client = $client;

        return $this;
    }

    /**
     * @return Collection|Lignedevis[]
     */
    public function getLignedevis(): Collection
    {
        return $this->lignedevis;
    }

    public function addLignedevi(Lignedevis $lignedevi): self
    {
        if (!$this->lignedevis->contains($lignedevi)) {
            $this->lignedevis[] = $lignedevi;
            $lignedevi->setDevis($this);
        }

        return $this;
    }

    public function removeLignedevi(Lignedevis $lignedevi): self
    {
        if ($this->lignedevis->removeElement($lignedevi)) {
            // set the owning side to null (unless already changed)
            if ($lignedevi->getDevis() === $this) {
                $lignedevi->setDevis(null);
            }
        }

        return $this;
    }

    public function convertcommande(){
        $commande = new Commande();

        $commande->setNom($this->getNom()); 
        $commande->setClient($this->getClient()); 
        $commande->setStatue($this->getStatue()); 
        foreach($this->getLignedevis() as $ligne ){

            $newligne = new LigneCommande(); 
            $newligne->setPrix($ligne->getPrix()); 
            $newligne->setQte($ligne->getQte()); 
            $newligne->setService($ligne->getService()); 
            $newligne->setCommande($commande);
            $commande->addLigneCommande($newligne);

        }
        return $commande;
        
    }
    public function getCreatedAt() :?DateTime
    {
        return $this->createdAt;
    }
    
    public function setCreatedAt(DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt() :?DateTime
    {
        return $this->updatedAt;
    }
    
    public function setUpdatedAt(DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getDateFormat(){
        return Outil::getDateFormatingsansday($this->createdAt->format('Y-m-d'));        
        return Outil::getDateFormatingsansday($this->updatedAt->format('Y-m-d'));
    }




    
    public function depluc(){ 
        $devi = new Devis(); 
        $devi->setClient($this->getClient()); 
        $devi->setStatue($this->getStatue());   
        foreach($this->getLignedevis() as $ligne ){ 
            $newligne = new Lignedevis(); 
            $newligne->setPrix($ligne->getPrix()); 
            $newligne->setQte($ligne->getQte()); 
            $newligne->setService($ligne->getService()); 
            $newligne->setDevis($devi);
            $devi->addLignedevi($newligne); 
        }
        return $devi; 
    }


}

src/Form/DevisType.php
<?php

namespace App\Form;

use App\Entity\Devis;
use App\Form\LignedevisType;
use App\Form\LignefactureType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class DevisType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('statue')
            ->add('client')
            ->add('lignedevis', CollectionType::class, [
                'entry_type' => LignedevisType::class,
                // 'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
                'label' => 'les services',
                'by_reference' => false,
                ])      
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Devis::class,
        ]);
    }
}

src/Controller/DevisController.php
<?php

namespace App\Controller;

use DateTime;
use Dompdf\Dompdf;
use Dompdf\Options;
use App\Entity\Devis;
use App\Entity\Clients;
use App\Form\DevisType;
use App\Entity\Lignedevis;
use App\Repository\DevisRepository;
use App\Repository\ClientsRepository;
use App\Repository\FactureRepository;
use App\Repository\ServiceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/devis")
*/
class DevisController extends AbstractController
{
    /**
     * @Route("/", name="devis_index", methods={"GET"})
    */
    public function index(DevisRepository $devisRepository): Response
    {
              
        return $this->render('devis/index.html.twig', [
            'devis' => $devisRepository->getDevis('expedier'),
        ]);
    }
    /**
     * @Route("/liste_a_voir", name="listeavoir", methods={"GET"})
    */
    public function listeavoir(DevisRepository $DevisRepository): Response
    {
        $devis = $DevisRepository->getDevisAnnuler('expedier');

        return $this->render('devis/listeavoir.html.twig', [
            'devis' => $devis
        ]);
    }

    /**
     * @Route("/{id}/devis", name="listedevisclient", methods={"GET", "POST"})
    */
    public function listedevisclient(Request $request,EntityManagerInterface $entityManager,ClientsRepository $ClientRepository,DevisRepository $devisRepository,$id): Response
    { 
        $client_selected = $ClientRepository->findOneBy(['id'=>$id]);
        
        if($client_selected){
            $client_select = $entityManager->getRepository(Clients::class)->find($client_selected);            
            $liste_devis = $entityManager->getRepository(Devis::class)->find($id);
            
            return $this->renderForm('devis/listedevis.html.twig', [
                'client_selected' => $client_selected,
                'liste_devis' => $liste_devis,
            ]);
          
        }
        else{
            echo "Client non exist";
            exit();
        }        
    }

     /**
     * @Route("/{id}/download", name="telecharger_devis_pdf", methods={"GET"})
     */
    public function telechargerdevispdf(Request $request,EntityManagerInterface $entityManager,Devis $devis,ClientsRepository $ClientRepository,DevisRepository $DevisRepository,$id): Response
    { 
        $devis = $DevisRepository->findOneBy(['id'=>$id]);

        $pdfoption = new Options();
        
        
        $pdfoption->set('Defaultfont','Arial');
        $pdfoption->setIsRemoteEnabled(true);
        
        
        $dompdf = new Dompdf($pdfoption);
        $context = stream_context_create([
            'ssl' => [
                'verify_peer' => false,
                'verify_peer_name' => false,
                'allow_self_signed' => true,
            ]
        ]);
        $dompdf ->setHttpContext($context);

        $html = $this->renderView('devis/imprimer.html.twig', [
                    'devis' => $devis
                ]);

        // Load HTML to Dompdf
        $dompdf->loadHtml($html);
        
        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (force download)
        $dompdf->stream("mypdf.pdf", [
            "Attachment" => true
        ]);

        return new Response($devis);
    }

    /**
     * @Route("/new", name="devis_new", methods={"GET", "POST"})
    */
    public function new(Request $request, ServiceRepository $ServiceRepository, EntityManagerInterface $entityManager): Response
    {
        $typeservice = $ServiceRepository->findAll();
        $devi = new Devis();
        $form = $this->createForm(DevisType::class, $devi);


        $form->handleRequest($request);
        
           
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($devi);

            $entityManager->flush();

            return $this->redirectToRoute('devis_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('devis/new.html.twig', [
            'devi' => $devi,
            'typeservice' => $typeservice,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/dupliquer_devis/{id}", name="dupliquer_devis", methods={"GET", "POST"})
    */
    public function dupliquerdevis(Request $request, EntityManagerInterface $entityManager,Devis $devi ): Response
    {        
        $new_devis =  $devi->depluc();  
     
        $form = $this->createForm(DevisType::class, $new_devis);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($new_devis);
            $entityManager->flush();
            return $this->redirectToRoute('devis_index', [], Response::HTTP_SEE_OTHER);
        }
        
        return $this->renderForm('devis/dupliquer.html.twig', [
            'devi' => $new_devis,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="devis_show", methods={"GET"})
    */
    public function show(Devis $devi): Response
    {
        return $this->render('devis/show.html.twig', [
            'devi' => $devi,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="devis_edit", methods={"GET", "POST"})
    */
    public function edit(Request $request, Devis $devi, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(DevisType::class, $devi);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->flush();

            return $this->redirectToRoute('devis_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('devis/edit.html.twig', [
            'devi' => $devi,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="devis_delete", methods={"POST"})
    */
    public function delete(Request $request, Devis $devi, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$devi->getId(), $request->request->get('_token'))) {
            $entityManager->remove($devi);
            $entityManager->flush();
        }

        return $this->redirectToRoute('devis_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/{id}/mail/", name="senddevismail", methods={"GET"})
    */
    public function contact(MailerInterface $mailer,Request $request,DevisRepository $DevisRepository,EntityManagerInterface $entityManager,$id): Response
    {       
        $devis = $DevisRepository->findOneBy(['id'=>$id]);
        $mail_id =  $request->query->get('mail','');
        $email = (new TemplatedEmail())
            ->from('alfalil.test@gmail.com')
            ->to($mail_id)
            ->subject('Devis')
            ->htmlTemplate('devis/contact.html.twig')
            ->context([
                'devis'=> $devis
            ]);
        $mailer->send($email);
        // return new Response();  
        return $this->redirectToRoute('devis_show', [
            'id' => $devis->getId(),'sts'=>'done',
        ], Response::HTTP_SEE_OTHER); 
                   
    }
}

templates/devis/_delete_form.html.twig
<form method="post" action="{{ path('devis_delete', {'id': devi.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ devi.id) }}">
    <button class="btn">Delete</button>
</form>

templates/devis/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/devis/contact.html.twig
{% block body %}

<style>

    /*
  Common invoice styles. These styles will work in a browser or using the HTML
  to PDF anvil endpoint.
*/

body {
  font-size: 16px;
}

table {
  width: 100%;
  border-collapse: collapse;
}

table tr td {
  padding: 0;
}

table tr td:last-child {
  text-align: right;
}

.bold {
  font-weight: bold;
}

.right {
  text-align: right;
}

.large {
  font-size: 1.75em;
}

.total {
  font-weight: bold;
  color: #fb7578;
}

.logo-container {
  margin: 20px 0 70px 0;
}

.invoice-info-container {
  font-size: 0.875em;
}
.invoice-info-container td {
  padding: 4px 0;
}

.client-name {
  font-size: 1.5em;
  vertical-align: top;
}

.line-items-container {
  margin: 70px 0;
  font-size: 0.875em;
}

.line-items-container th {
  text-align: left;
  color: #999;
  border-bottom: 2px solid #ddd;
  padding: 10px 0 15px 0;
  font-size: 0.75em;
  text-transform: uppercase;
}

.line-items-container th:last-child {
  text-align: right;
}

.line-items-container td {
  padding: 15px 0;
}

.line-items-container tbody tr:first-child td {
  padding-top: 25px;
}

.line-items-container.has-bottom-border tbody tr:last-child td {
  padding-bottom: 25px;
  border-bottom: 2px solid #ddd;
}

.line-items-container.has-bottom-border {
  margin-bottom: 0;
}

.line-items-container th.heading-quantity {
  width: 50px;
}
.line-items-container th.heading-price {
  text-align: right;
  width: 100px;
}
.line-items-container th.heading-subtotal {
  width: 100px;
}

.payment-info {
  width: 38%;
  font-size: 0.75em;
  line-height: 1.5;
}

.footer {
  margin-top: 100px;
}

.footer-thanks {
  font-size: 1.125em;
}

.footer-thanks img {
  display: inline-block;
  position: relative;
  top: 1px;
  width: 16px;
  margin-right: 4px;
}

.footer-info {
  float: right;
  margin-top: 5px;
  font-size: 0.75em;
  color: #ccc;
}

.footer-info span {
  padding: 0 5px;
  color: black;
}

.footer-info span:last-child {
  padding-right: 0;
}

.page-container {
  display: none;
}
.footer {
  margin-top: 30px;
}

.footer-info {
  float: none;
  position: running(footer);
  margin-top: -25px;
}

.page-container {
  display: block;
  position: running(pageContainer);
  margin-top: -25px;
  font-size: 12px;
  text-align: right;
  color: #999;
}

.page-container .page::after {
  content: counter(page);
}

.page-container .pages::after {
  content: counter(pages);
}


@page {
  @bottom-right {
    content: element(pageContainer);
  }
  @bottom-left {
    content: element(footer);
  }
}
</style>

{% set client_selected = devis.client %}

<div class="page-container">
    Page
    <span class="page"></span>
    of
    <span class="pages"></span>
  </div>
  
  <div class="logo-container">
    <img
      style="height: 18px"
      src="https://app.useanvil.com/img/email-logo-black.png"
    >
  </div>
  
  <table class="invoice-info-container">
    <tr>
      <td rowspan="2" class="client-name">
        Information client
      </td>
      <td>
       Raison Social : {{ client_selected.nom  }}
      </td>
    </tr>
    <tr>
      <td>
       Tél : {{ client_selected.telephone  }}
      </td>
    </tr>
    <tr>
      <td>
          
      </td>
      <td>
        Adresse : {{ client_selected.adress }}
      </td>
      <td>
        ICE : {{ client_selected.ice }}
      </td>
    </tr>
    <tr>
      <td>
        Invoice No: <strong>#00{{ devis.id }}</strong>
      </td>
    </tr>
  </table>
  
  
  <table class="line-items-container">
    <thead>
      <tr>
        <th class="heading-quantity">Nom Devis</th>
        <th class="heading-quantity"></th>
        <th class="heading-price">Price</th>
      </tr>
    </thead>
    <tbody>
        {% set total = 0  %}
            {% for lignefacture in devis.lignedevis %}
                <tr> 
                    <td >{{ lignefacture.service }}</td>
                    <td colspan="2" class="bold right">{{ lignefacture.prix }} DHS</td>

                </tr>
                
                    {% set  total = total +  lignefacture.prix %}
            {% else %}
                <tr>
                    <td colspan="5">il y a aucun devis dans votre table </td>
                </tr>
            {% endfor %}
                    {% set  taxes = (total * 20) / 100  %}

                </td>{{ total }}</td>
            </tr>
            <tr>
                <td colspan="2" class="text-end">total</td>
                <td >{{ total }} DHS</td>
            </tr>
            
        </tbody>
    </table>
  
  
  <table class="line-items-container has-bottom-border">
    <thead>
      <tr>
        <th>Info Paiement </th>
        <th></th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="payment-info">
          <div>
            Account No: <strong>{{ client_selected.ice }}</strong>
          </div>

        </td>
        <td class="large"></td>
        <td class="large total">{{ total }} Dhs</td>
      </tr>
    </tbody>
  </table>
  
  <div class="footer">
    <div class="footer-info">
      <span>hello@useanvil.com</span> |
      <span>555 444 6666</span> |
      <span>useanvil.com</span>
    </div>
</div>


{% endblock %}

templates/devis/dupliquer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer un devis{% endblock %}


    {% macro niceForme(form) %}
        <div class="row">
            <div class="col-md-5">
            {{ form_row(form.service) }}
            </div>
            <div class="col-md-1">
             <!-- Button trigger modal -->
                <button type="button" class="btn btn-outline-primary" class="btn btn-outline-primary m-2 add_item_link" data-collection-holder-class="lignesfacture_contenu" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    +
                </button>
            </div>
            <div class="col-md-2">
                {{ form_row(form.qte) }}
            </div>
            <div class="col-md-2">
            {{ form_row(form.prix) }}
            </div>
            <div class="col-md-2">            
                <button class="btn btn-danger btn-remove"   type="button">Supprimer</button>
            </div>
        </div>
     {% endmacro niceForme %}
     
{% block body %}
    <h1>Créer le devis</h1>

    {{ form_start(form) }}
    <div class="row">
        {# <div class="col-md-8">{{ form_row(form.nom) }}</div> #}
        <div class="col-md-8">{{ form_row(form.client) }}</div>
        <div class="col-md-8">{{ form_row(form.statue) }}</div>

    </div> 
    {% import _self as formMacros %} 
     
    <div class="row">
        <div class="listeligneorder">
            <h6> Les services </h6>
            <div class="lignesfacture_contenu col-md-12"
                data-index="{{ form.lignedevis|length > 0 ? form.lignedevis|last.vars.name + 1 : 0 }}"
                data-prototype="{{ formMacros.niceForme(form.lignedevis.vars.prototype)|e }}"> 
                {% for lig in form.lignedevis %}
                {{ formMacros.niceForme(lig) }}
                {% endfor %}
            </div>  
            <button type="button" class="btn btn-outline-primary mb-2 add_item_link" data-collection-holder-class="lignesfacture_contenu">
                Ajouter une ligne
            </button>
        </div> 
    </div>
    <div class="row"> 
        <div class="col-md-6"> 
            <button class="btn btn-outline-success">{{ button_label|default('Enregistrer') }}</button>       
        </div>
        <div class="col-md-6"> 
            <a class="btn btn-outline-primary" href="{{ path('clients_index') }}">Revenir à la liste des clients</a>    
        </div>
    </div>
{{ form_end(form) }}

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog">
    <div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ajouter un nouveau service</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        {{ render(url('service_new_ajax')) }}
    </div>
    <div class="modal-footer text-left">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
    </div>
    </div>
</div>
</div>
<script>
    

  $(document).ready(function () 
  {
    $("#serviceform").submit(function (event)
    {
      
    event.preventDefault();
    var formSerialize = $(this).serialize();
   
      $.ajax({
                url:"{{ path('service_new_ajax') }}",
                type: "POST",
                dataType: "json",
                data: formSerialize,
                async: true,
                encode: true,
                success: function (data) {
                console.log(data);
                },
                complete(xhr,status)
                {
                    $.ajax({
                        url:"{{ path('service_allservice') }}",
                        type: "POST",
                        async: true,
                        encode: true,
                        success: function (newlistservice)
                        {                            
                            $( ".choise_service" ).each(function( index ) {
                                //$(this).html(newlistservice);
                                 $(this).append(newlistservice);
                            }); 
                        }
                    });
                    $('#exampleModal').modal('hide');
                    $('.choise_service').lastchild('.choise_service');

                }
            });
        });
  });
</script>

{% endblock %}

templates/devis/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Facture index{% endblock %}
{% block stylesheetsnew %}
{% endblock %}

{% block body %}


   <h1> Liste devis </h1> 
    <a class="btn btn-outline-primary mb-2" href="{{ path('facture_new') }}">Ajouter devis </a>
    <table id="table2" class="table table-striped table-bordered">
        <thead>
            <tr> 
                <th>Référence</th>
                <th>Status</th>
                <th>client</th>
                <th>Date de création</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for de in devis %}
            <tr> 
                <td>{{ de.nom }}</td>
                <td>{{ de.statue }}</td>
                <td>{{ de.client.nom }}</td>
                <td>{{ de.dateFormat }}</td>

                <td>
                    <a  class="text-primary p-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="" data-bs-original-title="Afficher" aria-label="Views" href="{{ path('devis_show', {'id': de.id}) }}"><i class="bi bi-eye-fill"></i></a>
                    <a class="text-primary p-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="" data-bs-original-title="Editer" aria-label="Views" href="{{ path('devis_edit', {'id': de.id}) }}"><i class="bi bi-pencil-fill"></i></a>
                    {# <a class="text-primary p-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="" data-bs-original-title="Editer" aria-label="Views" href="{{ path('facture_edit', {'id': facture.id}) }}"><i class="bi bi-trash-fill"></i></a> #}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">il y a aucun devis dans votre table </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/devis/listeavoir.html.twig
{% extends 'base.html.twig' %}

{% block title %}Facture index{% endblock %}
{% block stylesheetsnew %}
{% endblock %}

{% block body %}


   <h1> Liste devis </h1> 
    <a class="btn btn-outline-primary mb-2" href="{{ path('facture_new') }}">Ajouter devis </a>


    <table id="table2" class="table table-striped table-bordered">
        <thead>
            <tr> 
                <th>Référence</th>
                <th>Status</th>
                <th>client</th>
                <th>Date de création</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for de in devis %}
            <tr> 
                <td>{{ de.nom }}</td>
                <td>{{ de.statue }}</td>
                <td>{{ de.client.nom }}</td>
                <td>{{ de.dateFormat }}</td>

                <td>
                    <a  class="text-primary p-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="" data-bs-original-title="Afficher" aria-label="Views" href="{{ path('devis_show', {'id': de.id}) }}"><i class="bi bi-eye-fill"></i></a>
                    <a class="text-primary p-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="" data-bs-original-title="Editer" aria-label="Views" href="{{ path('devis_edit', {'id': de.id}) }}"><i class="bi bi-pencil-fill"></i></a>
                    <a class="text-primary p-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="" data-bs-original-title="dupliquer" aria-label="dupliquer" href="{{ path('dupliquer_devis', {'id': de.id}) }}"><i class="bi bi-files"></i></a>
                    {# <a class="text-primary p-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="" data-bs-original-title="Editer" aria-label="Views" href="{{ path('facture_edit', {'id': facture.id}) }}"><i class="bi bi-trash-fill"></i></a> #}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">il y a aucun devis dans votre table </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}